package io.github.malczuuu.problem4j.spring.webflux.error;

import static io.github.malczuuu.problem4j.spring.web.context.ContextSupport.PROBLEM_CONTEXT;
import static io.github.malczuuu.problem4j.spring.web.util.ProblemSupport.resolveStatus;
import static org.springframework.web.reactive.function.server.RequestPredicates.all;
import static org.springframework.web.reactive.function.server.RouterFunctions.route;

import io.github.malczuuu.problem4j.core.Problem;
import io.github.malczuuu.problem4j.spring.web.context.ProblemContext;
import io.github.malczuuu.problem4j.spring.web.processor.ProblemPostProcessor;
import java.util.Optional;
import org.springframework.boot.autoconfigure.web.ErrorProperties;
import org.springframework.boot.autoconfigure.web.WebProperties;
import org.springframework.boot.autoconfigure.web.reactive.error.DefaultErrorWebExceptionHandler;
import org.springframework.boot.web.reactive.error.ErrorAttributes;
import org.springframework.context.ApplicationContext;
import org.springframework.http.MediaType;
import org.springframework.web.reactive.function.BodyInserters;
import org.springframework.web.reactive.function.server.RouterFunction;
import org.springframework.web.reactive.function.server.ServerRequest;
import org.springframework.web.reactive.function.server.ServerResponse;
import reactor.core.publisher.Mono;

/**
 * A WebFlux {@link org.springframework.boot.web.reactive.error.ErrorWebExceptionHandler} that
 * renders HTTP problems (RFC 7807) instead of the default JSON error response.
 *
 * <p>It replaces the response body with a {@link Problem} object while preserving the original HTTP
 * status and content type {@code application/problem+json}.
 */
public class ProblemErrorWebExceptionHandler extends DefaultErrorWebExceptionHandler {

  private final ProblemPostProcessor problemPostProcessor;

  /**
   * Creates a new {@code ProblemErrorWebExceptionHandler}.
   *
   * @param errorAttributes the error attributes used to obtain error details
   * @param resources configuration for static resources
   * @param errorProperties configuration for error handling
   * @param applicationContext the current application context
   */
  public ProblemErrorWebExceptionHandler(
      ProblemPostProcessor problemPostProcessor,
      ErrorAttributes errorAttributes,
      WebProperties.Resources resources,
      ErrorProperties errorProperties,
      ApplicationContext applicationContext) {
    super(errorAttributes, resources, errorProperties, applicationContext);
    this.problemPostProcessor = problemPostProcessor;
  }

  /**
   * Returns a routing function that handles all requests and delegates to {@code
   * #renderErrorResponse(ServerRequest)}.
   *
   * @param errorAttributes the error attributes used to resolve errors
   * @return a routing function for handling errors
   * @see #renderErrorResponse(ServerRequest)
   */
  @Override
  protected RouterFunction<ServerResponse> getRoutingFunction(ErrorAttributes errorAttributes) {
    return route(all(), this::renderErrorResponse);
  }

  /**
   * Renders an error response as a {@link Problem} in {@code application/problem+json} format.
   *
   * @param request the current server request
   * @return a {@link Mono} emitting the problem response
   */
  @Override
  protected Mono<ServerResponse> renderErrorResponse(ServerRequest request) {
    return super.renderErrorResponse(request).flatMap(res -> override(request, res));
  }

  /**
   * Overrides the default error response with a {@link Problem} body.
   *
   * @param request the current server request
   * @param response the response generated by the default handler
   * @return a {@link Mono} emitting the updated response
   */
  private Mono<ServerResponse> override(ServerRequest request, ServerResponse response) {
    Problem problem = Problem.builder().status(resolveStatus(response.statusCode())).build();

    Optional<ProblemContext> optionalContext =
        request.attribute(PROBLEM_CONTEXT).map(context -> (ProblemContext) context);
    if (optionalContext.isPresent()) {
      ProblemContext context = optionalContext.get();
      problem = problemPostProcessor.process(context, problem);
    }

    return ServerResponse.status(problem.getStatus())
        .contentType(MediaType.APPLICATION_PROBLEM_JSON)
        .body(BodyInserters.fromValue(problem));
  }
}
