name: Gradle Build

# workflow limited to only files related to gradle build itself
on:
  push:
    branches: [ "main" ]
    paths:
      - "problem4j-spring-*/build.gradle.kts"
      - "problem4j-spring-*/src/**"
      - "build.gradle.kts"
      - "settings.gradle.kts"
      - "gradle.properties"
      - "gradle/**"
      - "buildSrc/**"
      - "gradlew"
      - "gradlew.bat"
      - ".github/workflows/gradle-build.yml"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "temurin"

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew build
